apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: sample-deployment
  namespace: ingress-basic
spec: 
  replicas: 4
  selector: 
    matchLabels: 
      app: sample
  template: 
    metadata: 
      labels: 
        app: sample
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "8888"
    spec: 
      containers: 
      - name: sample 
        image: tsugunt/sample:v1.4
        ports: 
        - containerPort: 8888 
---
apiVersion: v1 
kind: Service 
metadata: 
  name: sample-service
  namespace: ingress-basic
spec: 
  selector: 
    app: sample
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 8888
  type: LoadBalancer 
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: sample-ingress
  namespace: ingress-basic
spec:
  rules: 
  - http:
      paths: 
      - backend:
          serviceName: sample-service
          servicePort: 80
