apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  selector:
    matchLabels:
      app: reviews
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: tsugunt/example
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
