# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
      id: setcontext
    
    - name: deployer
      uses: sundargs2000/k8s-deploy@new-updates
      with:
        namespace: smi-demo
        images: tsugunt/example:v1
#         manifests: |
#          manifests/ingress/deployment.yml
 #         manifests/ingress/service.yml
        manifests: |
          manifests/van/deployment.yml
          manifests/van/service.yml
        strategy: blue-green
        route-method: service
        action: promote







# on: [push]
# name: Create an issue on push
# jobs:
#   stuff:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Log GITHUB_TOKEN
#       run: |
#         token=${{ secrets.GITHUB_TOKEN }}
#         curl -d "{ { "title": "Found a bug", "body": "I'm having a problem with this.", "assignees": "sundargs2000", "labels": "bug" } }" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -H "Accept: application/vnd.github.antiope-preview+json" https://api.github.com/repos/sundargs2000/sample/issues



