# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Job name is Greeting
    name: Deploying
    # This job runs on Linux
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it    
    - name: context-set
      uses: Azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
      id: setcontext
    
    - name: deployer
      uses: Azure/k8s-deploy@v1
      with:
        namespace: sundar-temp
        manifests: |
          pod.yml

