name: CI
on:
  [push]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    
    env:
      deploy_image: tsugunt/sample:v22
      deploy_ns: ingress-basic
      deploy_manifest: ingress.yml
      deploy_route: ingress
    
    steps:
    - name: checkout 
      uses: actions/checkout@v2

    - name: k8-setup
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} 
      id: setcontext
      
    - name: k8-deployer-${{env.deploy_route}}
      uses: sundargs2000/k8s-deploy@new-test
      with:
        namespace: ${{env.deploy_ns}}
        images: ${{env.deploy_image}}
        manifests: |
          ${{env.deploy_manifest}}
        strategy: blue-green
        route-method: ${{env.deploy_route}}
        action: promote
                
#     - name: Create an issue
#       run: |
#         token=${{ secrets.GITHUB_TOKEN }}
#         curl -d '{"title": "Action needed", "body": "label promote or reject", "labels": [ "kube_ns:${{env.deploy_ns}}", "manifest:${{env.deploy_manifest}}", "route:${{env.deploy_route}}", "image-${{env.deploy_image}}" ] }' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -H "Accept: application/vnd.github.antiope-preview+json" https://api.github.com/repos/sundargs2000/sample/issues
