name: CI
on:
  [push]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    env:
      kube_ns: voting
      dock_image: mcr.microsoft.com/aks/samples/voting/analytics:1.0
      route_method: smi
    steps:

    - name: checkout 
      uses: actions/checkout@v2

    - name: k8-setup
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} 
      id: setcontext
    
    - name: k8-deployer
      uses: sundargs2000/k8s-deploy@reviews
      with:
        namespace: ${{env.kube_ns}}
        images: ${{env.dock_image}}
        manifests: |
          pod.yml
        strategy: blue-green
        route-method: ${{env.route_method}}
        action: deploy
    
    - name: Log GITHUB_TOKEN
      run: |
        token=${{ secrets.GITHUB_TOKEN }}
        curl -d '{"title": "Action needed", "body": "Edit title to promote-bg or reject-bg", "labels": [ "${{env.kube_ns}}", "${{env.dock_image}}", "${{env.route_method}}"] }' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -H "Accept: application/vnd.github.antiope-preview+json" https://api.github.com/repos/sundargs2000/sample/issues








#     service
#     - name: deployer
#       uses: sundargs2000/k8s-deploy@reviews
#       with:
#         namespace: smi-demo
#         images: tsugunt/example:v1
#         manifests: |
#           manifests/van/deployment.yml
#           manifests/van/service.yml
#         strategy: blue-green
#         route-method: smi
#         action: reject
        
    #ingress
#     - name: deployer
#       uses: sundargs2000/k8s-deploy@reviews
#       with:
#         namespace: ingress-basic
#         images: tsugunt/sample:v22
#         manifests: |
#          manifests/ingress/deployment.yml
#          manifests/ingress/service.yml
#          manifests/ingress/ingress.yml
#         strategy: blue-green
#         route-method: ingress
#         action: reject

