on:
  issues:
    types: [edited]
name: promote-reject-bg
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: printing event
        env:
          var1: ${{github.event.issue.url}}
          var2: "/labels"
        run: |
          curl $var1$var2
  promote:
    if: github.event.issue.title == 'promote-bg'
    runs-on: ubuntu-latest
    steps:
    - name: Printing promote
      run: |
        echo time to promote  
  reject:
    if: github.event.issue.title == 'reject-bg'
    runs-on: ubuntu-latest
    steps:
    - name: Printing reject
      run: |
        echo time to reject
