on:
  issues:
    types: [labeled]
name: promote-reject-bg
jobs:
  promote:
    if: github.event.label.name == 'promote-bg'
    runs-on: ubuntu-latest
    steps:
    - name: Printing promote
      run: |
        echo time to promote  
  reject:
    if: github.event.label.name == 'reject-bg'
    runs-on: ubuntu-latest
    steps:
    - name: Printing reject
      run: |
        echo time  to reject
