on:
  issues:
    types: [labeled]
    
name: promote-reject-bg
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: printing event
        run: |
          echo ${{github.event.label.name}}
  promote-reject:
    runs-on: ubuntu-latest
    steps:
    - name: Printing promote
      run: |
        echo time to promote  
        
    - name: checkout 
      uses: actions/checkout@v2

    - name: k8-setup
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} 
      id: setcontext
    
    - name: k8-deployer-${{github.event.label.name}}
      uses: sundargs2000/k8s-deploy@reviews
      with:
        namespace: ${{github.event.issue.labels[0].name}}
        images: ${{github.event.issue.labels[1].name}}
        manifests: |
          pod.yml
        strategy: blue-green
        route-method: ${{github.event.issue.labels[2].name}}
        action: ${{github.event.label.name}}
        
