on:
  issues:
    types: [labeled]
    
name: promote-reject-bg
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: printing event
        run: |
          echo ${{github.event.issue.labels[0].name}}
  promote:
    if: github.event.issue.title == 'promote-bg'
    runs-on: ubuntu-latest
    steps:
    - name: Printing promote
      run: |
        echo time to promote  
        
    - name: checkout 
      uses: actions/checkout@v2

    - name: k8-setup
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} 
      id: setcontext
    
    - name: k8-deployer
      uses: sundargs2000/k8s-deploy@reviews
      with:
        namespace: voting
        images: ${{github.event.issue.labels[0].name}}
        manifests: |
          pod.yml
        strategy: blue-green
        route-method: smi
        action: promote
        
  reject:
    if: github.event.issue.title == 'reject-bg'
    runs-on: ubuntu-latest
    steps:
    - name: Printing reject
      run: |
        echo time to reject
    
    - name: checkout 
      uses: actions/checkout@v2

    - name: k8-setup
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} 
      id: setcontext
    
    - name: k8-deployer
      uses: sundargs2000/k8s-deploy@reviews
      with:
        namespace: voting
        images: ${{github.event.issue.labels[0].name}}
        manifests: |
          pod.yml
        strategy: blue-green
        route-method: smi
        action: reject
