on:
  issues:
    types: [labeled]
    
name: promote-reject-bg
jobs:
  promote-reject:
    runs-on: ubuntu-latest
    
    env:
      dp_image: none
    
    steps:
    - name: Setting environment
      run: |
        api=$(curl ${{github.event.issue.url}})
        image=$(echo "$api" | grep image | grep name | awk '{print $2}' | grep image |  cut -d'-' -f 2 | cut -d'"' -f 1 )
        echo "$image"
        echo "::set-env name=dp_image::$image"
#        echo "${{github.event.issue.labels}}[*]" | grep image
      shell: bash
      
    - name: checking environment
      run: |
        echo "${{env.dp_image}}"
      shell: bash
        
#     - name: checkout 
#       uses: actions/checkout@v2

#     - name: k8-setup
#       uses: azure/k8s-set-context@v1
#       with:
#         method: kubeconfig
#         kubeconfig: ${{ secrets.KUBE_CONFIG }} 
#       id: setcontext
    
#     - name: k8-deployer-${{github.event.label.name}}
#       uses: sundargs2000/k8s-deploy@reviews
#       with:
#         namespace: voting
#         images: ${{github.event.issue.labels[0].name}}
#         manifests: |
#           pod.yml
#         strategy: blue-green
#         route-method: smi
#         action: ${{github.event.label.name}}
  

